name: Basic workflow

on:
  workflow_dispatch

jobs:
  print_something:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Github
        uses :  actions/checkout@v3

      - name : List Files
        run  : ls ./

      - name : Get Prayer Time
        run  : |
          curl -H "Accept: application/json" "https://www.e-solat.gov.my/index.php?r=esolatApi/TakwimSolat&period=today&zone=WLY01"





