name: Basic workflow

on:
  workflow_dispatch

jobs:
  print_something:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Github
        uses :  actions/checkout@v3

      - name : List Files
        run  : ls ./
      - name: Fetch Prayer Times with User-Agent
        run: |
          curl --location --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" \
               -H "Accept: application/json" \
               "https://api.sampleapis.com/beers/ale"
               -o myresponse.json







