name: Deploy to Production

on:
  workflow_run:
    workflows: [ "Build and Push" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Deploy to production environment
      uses: appleboy/ssh-action@master
      with:
        host: 118.107.233.236
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ./imaginur-backend
          docker compose pull
          # Run twice to ensure latest image is pulled
          docker compose up --force-recreate --build -d
          docker compose up --force-recreate --build -d
          docker system prune -a -f